# Generated by Django 5.0.1 on 2024-02-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_login_password_login_username_login_usertype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(default="SOME STRING", max_length=20)),
                ("date", models.CharField(default="SOME STRING", max_length=20)),
                ("alert_image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Forest_Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division_name",
                    models.CharField(default="SOME STRING", max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="SOME STRING", max_length=20)),
                ("description", models.CharField(default="SOME STRING", max_length=20)),
                ("date", models.CharField(default="SOME STRING", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animal_name", models.CharField(default="SOME STRING", max_length=20)),
                ("animal_image", models.ImageField(upload_to="")),
                (
                    "animal_description",
                    models.CharField(default="SOME STRING", max_length=20),
                ),
                ("safety_tips", models.CharField(default="SOME STRING", max_length=20)),
                (
                    "FOREST_DIVISION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.forest_division",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Forest_Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(default="SOME STRING", max_length=20),
                ),
                ("place", models.CharField(default="SOME STRING", max_length=20)),
                (
                    "contact_number",
                    models.CharField(default="SOME STRING", max_length=20),
                ),
                (
                    "FOREST_DIVISION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.forest_division",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Allocate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="SOME STRING", max_length=20)),
                (
                    "FOREST_OFFICER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.forest_officer",
                    ),
                ),
                (
                    "FOREST_STATION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.forest_station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Preserved_Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ANIMAL",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(default="SOME STRING", max_length=20)),
                ("lname", models.CharField(default="SOME STRING", max_length=20)),
                ("place", models.CharField(default="SOME STRING", max_length=20)),
                ("phone", models.CharField(default="SOME STRING", max_length=20)),
                ("email", models.CharField(default="SOME STRING", max_length=20)),
                (
                    "FOREST_STATION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.forest_station",
                    ),
                ),
                (
                    "LOGIN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.login"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emergency_Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_image", models.ImageField(upload_to="")),
                ("description", models.CharField(default="SOME STRING", max_length=20)),
                (
                    "USER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="SOME STRING", max_length=20)),
                ("description", models.CharField(default="SOME STRING", max_length=20)),
                ("reply", models.CharField(default="SOME STRING", max_length=20)),
                ("date", models.CharField(default="SOME STRING", max_length=20)),
                (
                    "USER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(default="SOME STRING", max_length=20)),
                ("date", models.CharField(default="SOME STRING", max_length=20)),
                (
                    "FOREST_OFFICER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.forest_officer",
                    ),
                ),
                (
                    "USER",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
        ),
    ]
