# Generated by Django 5.0.1 on 2024-03-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_forest_division_notification_login_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="description",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
        migrations.AlterField(
            model_name="animal",
            name="safety_tips",
            field=models.CharField(default="SOME STRING", max_length=50),
        ),
        migrations.AlterField(
            model_name="chat",
            name="message",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="description",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="reply",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
        migrations.AlterField(
            model_name="emergency_message",
            name="description",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
        migrations.AlterField(
            model_name="forest_officer",
            name="email",
            field=models.CharField(default="SOME STRING", max_length=30),
        ),
        migrations.AlterField(
            model_name="notification",
            name="description",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(default="SOME STRING", max_length=30),
        ),
    ]
