# Generated by Django 5.0.1 on 2024-02-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alert_forest_division_notification_animal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="animal_description",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
    ]
