# Generated by Django 5.0.1 on 2024-03-19 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_emergency_message_message_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="LOGIN",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.login"
            ),
            preserve_default=False,
        ),
    ]
