# Generated by Django 5.0.1 on 2024-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_alert_alert_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="animal_image",
            field=models.ImageField(upload_to="static/animal"),
        ),
    ]
