# Generated by Django 5.0.1 on 2024-03-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_chat_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="LOGIN",
        ),
        migrations.AddField(
            model_name="chat",
            name="usertype",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
