# Generated by Django 5.0.1 on 2024-03-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_chat_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="description",
            field=models.CharField(default="SOME STRING", max_length=1000),
        ),
    ]
